//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hi_Tech_Order_Management_System.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<System.DateTime> PlacedDate { get; set; }
        public Nullable<System.DateTime> ArrivingDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        public virtual Order Orders1 { get; set; }
        public virtual Order Order1 { get; set; }
        public virtual Order Orders11 { get; set; }
        public virtual Order Order2 { get; set; }
    }
}
