//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insertimage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carinfo
    {
        public int carid { get; set; }
        public string CarModel { get; set; }
        public string CarType { get; set; }
        public byte[] Carimage { get; set; }
    }
}
