//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exampleregistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillingDetail()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
        }
    
        public int Billid { get; set; }
        public System.DateTime BillDate { get; set; }
        public double TotalAmount { get; set; }
        public int BookingId { get; set; }
        public int Customer_Id { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
    }
}
