//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMTITeacher_CourseManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseAssignment
    {
        public int EmployeeId { get; set; }
        public string CourseCode { get; set; }
        public int GroupNumber { get; set; }
        public System.DateTime AssignedDate { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Group Group { get; set; }
    }
}
