//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMTITeacher_CourseManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Data.SqlClient;

    public partial class User
    {
        [Required(ErrorMessage = "Required.")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Required.")]
        public string Password { get; set; }


        //This method validates the Login credentials
        //public String LoginProcess(String strUsername, String strPassword)
        //{
        //    //String message = "";
        //    ////my connection string
        //    ////SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["connectionString"].ConnectionString);
        //    //SqlCommand cmd = new SqlCommand("Select * from User where Username=@Username", con);
        //    //cmd.Parameters.AddWithValue("@Username", strUsername);
        //    //try
        //    //{
        //    //    con.Open();
        //    //    SqlDataReader reader = cmd.ExecuteReader();
        //    //    if (reader.Read())
        //    //    {
        //    //        Boolean login = (strPassword.Equals(reader["Password"].ToString(), StringComparison.InvariantCulture)) ? true : false;
        //    //        if (login)
        //    //        {
        //    //            message = "1";
        //    //            UserName = reader["UserName"].ToString();

        //    //        }
        //    //        else
        //    //            message = "Invalid Credentials";
        //    //    }
        //    //    else
        //    //        message = "Invalid Credentials";

        //    //    reader.Close();
        //    //    reader.Dispose();
        //    //    cmd.Dispose();
        //    //    con.Close();
        //    //}
        //    //catch (Exception ex)
        //    //{
        //    //    message = ex.Message.ToString() + "Error.";

        //    //}
        //    //return message;
        //}
    }
}
